[tool.poetry]
name = "ragbase"
version = "0.1.1"
description = ""
authors = ["Venelin Valkov <venelin@curiousily.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
langchain-community = "^0.3.29"
flashrank = "^0.2.10"
qdrant-client = "^1.15.1"
pypdfium2 = "^4.30.0"
fastembed = "^0.7.3"
langchain-experimental = "^0.3.4"
langchain-qdrant = "^0.2.1"
streamlit = "^1.49.1"
python-dotenv = "^1.1.1"
langchain-groq = "^0.3.8"


[tool.poetry.group.dev.dependencies]
ruff = "^0.13.1"
jupyterlab = "^4.4.7"
watchdog = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
